### ISSUE TITLE
Components gone until page is clicked

### ISSUE THREAD

**Issue by StefanDorschu** [illacloud/illa-builder#1957]
### Description

All components are not showing up until i click on the corresponding page. 

### Steps to reproduce

While in editing mode thats not a problem at all, when launching the app /deploying it stops working

### ILLA Builder Version

2.9.5

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

https://github.com/illacloud/illa-builder/assets/24601959/397a606b-8872-4905-80b9-090f10b8662d

**Comment by HabelStefan** [comment]
Maybe i found a reason for this bug.

I have the following structure:

1 page with several views.

<img width="300" alt="Bildschirmfoto 2023-07-25 um 06 20 06" src="https://github.com/illacloud/illa-builder/assets/24601959/21a64b66-a2a3-470e-92ba-9af53fb1b870">

As you can see i have set the default view to marketing_schulen. But every time i load the app it show the -marketing_veranstaltungen page when i am in the edit mode.

The bug has gone when i renamed the view "marketing-veranstaltungen" to "-marketing-veranstaltungen".

Maybe this will help you find the root cause for this behavior.

**Comment by AruSeito** [comment]
Hello,
Can you open the ChromeDevTools to check if there are any error messages?
You can press command+option+i to open it.and then click [console],does it have error message?

**Comment by HabelStefan** [comment]
Thank you for your reply, if that problem occurs again, i will give you an update.

**Comment by AruSeito** [comment]
Hello, have you encountered this bug recently?

**Comment by StefanDorschu** [comment]
no, not this bug but sometimes renaming subpages takes some tries or just does not update.

**Comment by AruSeito** [comment]
We have made new changes to the page and subpage. If you encounter this issue again in the future, please open the issue again
